- name: Docker host configuration
  hosts: all
  remote_user: root
  become: yes
  vars:
    path: /etc/checks
  tasks:
    - name: executing CIS number 1
      shell: "{{ path }}/check1.{{ item }} >> /tmp/log1-{{ inventory_hostname }}"
      loop:
        - 1.1
        - 1.2
        - 1.3
        - 1.4
        - 1.5
        - 1.6
        - 1.7
        - 1.8
        - 1.9
        - 1.10
        - 2.1
        - 2.2
    - name: copy file from remote server
      fetch:
        src: /tmp/log1-{{ inventory_hostname }}
        dest: /tmp/log1-{{ inventory_hostname }}
        mode: 0774
        flat: yes
