- name: Docker host configuration
  hosts: all
  remote_user: root
  become: yes
  vars:
    path: /etc/checks
  tasks:
    - name: executing CIS number 4
      shell: "{{ path }}/check4.{{ item }} >> /tmp/log4-{{ inventory_hostname }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
    - name: copy file from remote server
      fetch:
        src: /tmp/log4-{{ inventory_hostname }}
        dest: /tmp/log4-{{ inventory_hostname }}
        mode: 0774
        flat: yes
