- name: Docker host configuration
  hosts: all
  remote_user: root
  become: yes
  vars:
    path: /etc/checks
  tasks:
    - name: executing CIS number 5
      shell: "{{ path }}/check5.{{ item }} >> /tmp/log5-{{ inventory_hostname }}"
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
    - name: copy file from remote server
      fetch:
        src: /tmp/log5-{{ inventory_hostname }}
        dest: /tmp/log5-{{ inventory_hostname }}
        mode: 0774
        flat: yes
